language: ruby

sudo: required
cache: bundler

services:
 - mysql

dist: trusty

before_install:
  - jdk_switcher use openjdk8
  - ./.travis-install-dependencies.sh

before_script:
  - jdk_switcher use $JDK

notifications:
  email:
    - kill-bill-commits@googlegroups.com

env:
  global:
    - RAILS_ENV=test MYSQL_PASSWORD='root' MYSQL_USER='root' JRUBY_OPTS='--2.0 -J-Xmx1024m'

rvm:
  - 2.4.0
  - jruby-9.1.12.0
  - ruby-head
  - jruby-head

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
