language: ruby

sudo: required
cache: bundler

services:
 - mysql
 - postgresql

dist: trusty

before_install:
  - jdk_switcher use openjdk8
  - ./.travis-install-dependencies.sh

before_script:
  - jdk_switcher use $JDK

notifications:
  email:
    - kill-bill-commits@googlegroups.com

env:
  global:
    - RAILS_ENV=test DB_PASSWORD='' JRUBY_OPTS='-J-Xmx1024m --debug -J-Djava.security.egd=file:/dev/./urandom'
  matrix:
    - DB_ADAPTER=mysql2 DB_USER='root' DB_PORT=3306
    - DB_ADAPTER=mariadb DB_USER='root' DB_PORT=3306
    - DB_ADAPTER=postgresql DB_USER='postgres' DB_PORT=5432

rvm:
  - 2.4.0
  - jruby-9.1.12.0
  - ruby-head
  - jruby-head

matrix:
  exclude:
    - rvm: 2.4.2
      env: DB_ADAPTER=mariadb DB_USER='root' DB_PORT=3306
    - rvm: ruby-head
      env: DB_ADAPTER=mariadb DB_USER='root' DB_PORT=3306
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
