language: ruby

notifications:
  email:
    - kill-bill-commits@googlegroups.com

rvm:
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - ruby-head
  - jruby-19mode
  - jruby-20mode
  - jruby-head

jdk:
  - openjdk6
  - openjdk7
  - oraclejdk7

before_script:
  - mysql -e 'create database kaui_test;'

script:
  - pushd test/dummy && RAILS_ENV=test bundle exec rake db:migrate --trace && RAILS_ENV=test bundle exec rake db:test:prepare && popd
  - bundle exec rake test:units

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head

env:
  - MYSQL_PASSWORD=''

#force travis to use only 'bundle install' instead of 'bundle install --deployments'
bundler_args: ''
